import blockContent from './blockContent'
import category from './category'
import post from './post'
import author from './author'
import social from './social'
import pageInfo from './pageInfo'
import faqs from './faqs'
import services from './services'
import listing from './listing'
import bulletSection from './bulletSection'
import trustedBy from './trustedBy'
import testimonials from './testimonials'
import transactions from './transactions'

export const schemaTypes = [transactions, listing, trustedBy, services,  bulletSection, pageInfo, testimonials, social, faqs, author, category, blockContent]
